"""Act III figure panels for paper 2 (M1 high-flux campaign, R18-frozen).

Five Act-III panels + one hero mechanism figure, written to paper2/figs/ as
standalone PDFs (+ PNG previews). Style follows the round-63 paper figure
scripts (serif fonts, colourblind-safe Wong palette, pdf.fonttype 42) and the
Chen-group optics house style (large legible fonts, obvious guard bars,
in-panel metrics).

Panels (spec: R18 ruling Sec 4.5 / Sec 6, docs/ROUND63_GPT_ROUND18_RULING_RAW):
  (a) Guard-collapse DEV plot (development evidence): dose deviation, A-risk
      ratio, spectral floor vs path-specific alpha (descending mixture scan)
      for the DEV glyph cell. Data cached by the precompute in
      results/round63_m1/ACTIII_A_GUARD_TRAJECTORY.json (regenerated by the
      frozen oed_design_v5.design_v5 -> mixture_search / path_feasible_alpha
      machinery if absent).
  (b) Constructive dose-only primal lower bounds (DEV-only): the frozen
      12-cell replication table (results/round63_m1/R18_GAP_PROBE_REPLICATION
      .md), all six families x two anchors, D-efficiency = exp(gap).
  (c) Confirmatory FULL_STACK_CERT distribution (descriptive branch): status
      counts by the four (nu,b) anchors + the COUNTEREXAMPLE primal-gap
      distribution, from results/round63_m1/shards/M1_CERT_*.csv (480 rows).
  (d) CENTREPIECE: ridge-vs-0.60 fixed-dwell result. Reconstruction thumbnails
      (GT | SCAT32-060 | RIDGE-SCAT32) for the three disclosed cells
      (median/best/worst dQ), each annotated with PSNR_rad + a per-row dQ
      badge, plus a compact 24-point dQ dot strip. Recons cached in
      results/round63_m1/ACTIII_D_RECON.npz.
  (e) Resource-corner schematic (drawing): the conjugate-corners doctrine with
      the two M1 verdicts stamped as badges.
  mechanism: hero Fig.-1 schematic (source+power dial -> DMD/SCAT32 ->
      object -> single-pixel detector+dead-time timeline -> reconstruction)
      beside the count-information ridge law J(rho) with rho*(nu) marked.

Run (cwd = repo root D:\\GI_another):
    D:\\Anacondar\\anaconda3\\python.exe code\\round63\\figs\\fig_actiii_panels.py
Individual panels: pass panel letters, e.g. `... fig_actiii_panels.py b c e`.
"""
import json
import glob
import os
import sys

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import gridspec
import matplotlib.transforms as mtransforms
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle
from matplotlib.lines import Line2D

HERE = os.path.dirname(os.path.abspath(__file__))            # code/round63/figs
R63 = os.path.dirname(HERE)                                  # code/round63
REPO = os.path.dirname(os.path.dirname(R63))                 # repo root
OUT_DIR = os.path.join(REPO, "paper2", "figs")
M1 = os.path.join(REPO, "results", "round63_m1")
SHARDS = os.path.join(M1, "shards")

# ---- Wong colourblind-safe palette --------------------------------------- #
BLUE = "#0072B2"      # anchor A / SCAT32-060 / balanced
ORANGE = "#D55E00"    # anchor B / worst / vermillion
GREEN = "#009E73"     # pass / ridge win
AMBER = "#E69F00"
SKY = "#56B4E9"
PINK = "#CC79A7"
YELLOW = "#F0E442"
GREY = "#666666"
RED = "#C4342B"
FAM_COLOR = {"glyph": BLUE, "chirp": AMBER, "maze": GREEN,
             "spokes": SKY, "contour": ORANGE, "microtexture": PINK}
FAM_ORDER = ["glyph", "chirp", "maze", "spokes", "contour", "microtexture"]


def setup_style():
    plt.rcParams.update({
        "font.family": "serif",
        "font.size": 9,
        "axes.linewidth": 0.7,
        "axes.labelsize": 9.5,
        "axes.titlesize": 10,
        "xtick.labelsize": 8.5,
        "ytick.labelsize": 8.5,
        "legend.fontsize": 8,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "figure.dpi": 120,
    })


def _save(fig, name):
    os.makedirs(OUT_DIR, exist_ok=True)
    pdf = os.path.join(OUT_DIR, name + ".pdf")
    png = os.path.join(OUT_DIR, name + ".png")
    fig.savefig(pdf)
    fig.savefig(png, dpi=200)
    plt.close(fig)
    print("[figs] wrote %s (+ .png)" % pdf, flush=True)


def _fnum(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return float("nan")


def _read_md_table(path, must_have):
    """Return (header, rows) of the first GitHub-md table containing all
    `must_have` column names."""
    text = open(path, encoding="utf-8").read()
    lines = text.splitlines()
    i, n = 0, len(lines)
    while i < n:
        ln = lines[i].strip()
        if (ln.startswith("|") and i + 1 < n
                and set(lines[i + 1].strip()) <= set("|-: ")):
            header = [c.strip() for c in ln.strip("|").split("|")]
            rows = []
            j = i + 2
            while j < n and lines[j].strip().startswith("|"):
                rows.append([c.strip()
                             for c in lines[j].strip().strip("|").split("|")])
                j += 1
            if all(m in header for m in must_have):
                return header, rows
            i = j
        else:
            i += 1
    raise SystemExit("no md table with %s in %s" % (must_have, path))


# ========================================================================== #
#  cert CSV reader (overflow-merge for comma-bearing solver_status fields)    #
# ========================================================================== #
def _read_cert_csv(path):
    with open(path, encoding="utf-8") as f:
        hdr = f.readline().strip().split(",")
        rows = []
        for line in f:
            parts = line.rstrip("\n").split(",")
            if len(parts) > len(hdr):
                i0 = hdr.index("solver_status_primary")
                extra = len(parts) - len(hdr)
                parts = (parts[:i0] + [",".join(parts[i0:i0 + 1 + extra])]
                         + parts[i0 + 1 + extra:])
                if len(parts) > len(hdr):
                    i1 = hdr.index("solver_status_retry")
                    extra = len(parts) - len(hdr)
                    parts = (parts[:i1] + [",".join(parts[i1:i1 + 1 + extra])]
                             + parts[i1 + 1 + extra:])
            rows.append(dict(zip(hdr, parts)))
    return rows


def _load_cert():
    rows = []
    for p in sorted(glob.glob(os.path.join(SHARDS, "M1_CERT_*.csv"))):
        rows.extend(_read_cert_csv(p))
    assert len(rows) == 480, "cert accounting: %d != 480" % len(rows)
    return rows


# ========================================================================== #
#  PANEL (a): guard-collapse DEV plot                                         #
# ========================================================================== #
A_JSON = os.path.join(M1, "ACTIII_A_GUARD_TRAJECTORY.json")


def _ensure_a_trajectory():
    if os.path.exists(A_JSON):
        return json.load(open(A_JSON))
    raise SystemExit(
        "panel (a) needs %s; run the precompute first:\n"
        "  D:/Anacondar/anaconda3/python.exe "
        "<scratchpad>/precompute_a.py\n"
        "(runs oed_design_v5.design_v5 -> mixture_search on the DEV glyph "
        "fast anchor; <=~15 min)." % A_JSON)


def panel_a():
    d = _ensure_a_trajectory()
    alpha = np.array(d["alpha"])
    dose = np.array(d["dose_dev"])
    arisk = np.array(d["arisk_ratio"])
    mu = np.array(d["mu_min"])
    bars = d["guard_bars"]
    # sort ascending in alpha for a clean left->right OED fraction axis
    o = np.argsort(alpha)
    alpha, dose, arisk, mu = alpha[o], dose[o], arisk[o], mu[o]

    fig, ax = plt.subplots(figsize=(4.1, 3.4))
    ax.set_yscale("log")
    # any adaptive fraction (alpha>0) is dose-infeasible: shade the band
    ax.axvspan(alpha[alpha > 0].min(), 1.02, color=RED, alpha=0.05, zorder=0)
    # three raw guard series
    ax.plot(alpha, dose, color=ORANGE, lw=1.9, label="dose deviation",
            zorder=4)
    ax.plot(alpha, mu, color=GREEN, lw=1.9,
            label=r"spectral floor $\mu_{\min}$", zorder=4)
    ax.plot(alpha, arisk, color=BLUE, lw=1.9,
            label=r"A-risk ratio tr$(V^{-1})/$tr$(V_{\rm fix}^{-1})$",
            zorder=4)
    # guard bars (matched colours) with left-margin value labels
    for val, col, txt, va in (
            (bars["dose_dev"], ORANGE, r"0.05  ($\pm$5% dose)", "top"),
            (bars["spectral_mu_min"], GREEN, r"0.5$\times$  spectral floor",
             "bottom"),
            (bars["arisk_ratio"], BLUE, r"1.05$\times$  A-risk cap",
             "bottom")):
        ax.axhline(val, color=col, ls="--", lw=1.0, alpha=0.85)
        ax.text(0.02, val, txt, color=col, fontsize=6.6, va=va, ha="left",
                zorder=6, bbox=dict(boxstyle="round,pad=0.1", fc="white",
                                    ec="none", alpha=0.8))

    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(0.03, 15)
    ax.set_xlabel(r"path-specific OED fraction $\alpha = m/972$")
    ax.set_ylabel("guard quantity (log)")
    ax.set_title("(a) Adaptive mixture collapses under the conditioning "
                 "stack\n(development evidence, DEV glyph, "
                 r"$\nu{=}2000,\,b{=}0.60$)", fontsize=8.4)
    # only the trivial balanced endpoint is dose-feasible; it fails effD
    ax.plot([0.0], [dose[0]], "o", color=ORANGE, ms=6, mec="black",
            mew=0.6, zorder=6)
    ax.annotate(r"only $\alpha{=}0$ (balanced) is dose-feasible," "\n"
                r"but fails the effD $\geq 0.95$ floor", xy=(0.008, dose[0]),
                xytext=(0.24, 0.135), fontsize=6.6, ha="left", va="center",
                arrowprops=dict(arrowstyle="->", color=GREY, lw=0.7))
    ax.text(0.60, 6.0, r"dose 2–11$\times$ over cap" "\n"
            r"for every $\alpha>0$", fontsize=6.8, color=ORANGE, ha="center")
    ax.text(0.97, 0.42, "PATH_FEASIBLE_ALPHA = None\n"
            "NO_FEASIBLE_POINT_ON_PATH", fontsize=6.9, fontweight="bold",
            va="center", ha="right",
            bbox=dict(boxstyle="round,pad=0.25", fc="#fff3f0", ec=RED,
                      lw=0.9), zorder=6)
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.20), ncol=1,
              frameon=False, fontsize=7.0, handlelength=1.8,
              borderpad=0.2, labelspacing=0.25)
    fig.subplots_adjust(left=0.14, right=0.97, top=0.84, bottom=0.36)
    _save(fig, "actiii_a")


# ========================================================================== #
#  PANEL (b): constructive dose-only primal lower bounds (DEV-only)           #
# ========================================================================== #
def panel_b():
    path = os.path.join(M1, "R18_GAP_PROBE_REPLICATION.md")
    hdr, rows = _read_md_table(
        path, ["scene", "nu", "b", "DOSE_ONLY_PRIMAL_GAP_PER_R"])
    ig = hdr.index("DOSE_ONLY_PRIMAL_GAP_PER_R")
    isc, inu, ib = hdr.index("scene"), hdr.index("nu"), hdr.index("b")
    data = {}                              # family -> {anchor: gap}
    for r in rows:
        fam = r[isc].replace("m1_dev_", "")
        nu, b = _fnum(r[inu]), _fnum(r[ib])
        anchor = "A" if (nu == 2000.0 and b == 0.60) else "B"
        data.setdefault(fam, {})[anchor] = _fnum(r[ig])
    fams = [f for f in FAM_ORDER if f in data]

    fig, ax = plt.subplots(figsize=(3.9, 3.0))
    x = np.arange(len(fams))
    gA = [data[f]["A"] for f in fams]
    gB = [data[f]["B"] for f in fams]
    # paired stems + markers
    for xi, a, bb in zip(x, gA, gB):
        ax.plot([xi, xi], [min(a, bb), max(a, bb)], color=GREY, lw=1.0,
                zorder=1)
    ax.plot(x, gA, "o", color=BLUE, ms=7, zorder=3,
            label=r"anchor A: $\nu{=}2000,\, b{=}0.60$")
    ax.plot(x, gB, "D", color=ORANGE, ms=6, zorder=3,
            label=r"anchor B: $\nu{=}200,\, b{=}0.05$")
    ax.axhline(0.0, color="black", lw=0.6)
    ax.set_xticks(x)
    ax.set_xticklabels(fams, rotation=30, ha="right", fontsize=8)
    ax.set_ylabel(r"dose-only primal gap / $r$   ($\log\det$ per dim.)")
    ax.set_ylim(0.0, 1.05)
    ax.set_xlim(-0.5, len(fams) - 0.5)
    ax.set_title("(b) Dose-only geometry headroom is real\n"
                 "(development-only lower bound; no gate)", fontsize=9)
    # right axis: D-efficiency lower bound = exp(gap)
    sec = ax.secondary_yaxis("right", functions=(np.exp, np.log))
    sec.set_ylabel(r"$D$-efficiency lower bound  $\exp(\mathrm{gap})$")
    sec.set_yticks([1.0, 1.5, 2.0, 2.5])
    ax.legend(loc="lower center", frameon=False, fontsize=7.6,
              handletextpad=0.4, ncol=1)
    ax.text(0.02, 0.03, "support-preserving construction: existence, "
            "not optimum", transform=ax.transAxes, fontsize=6.6,
            color=GREY, style="italic")
    fig.subplots_adjust(left=0.15, right=0.85, top=0.86, bottom=0.22)
    with np.errstate(divide="ignore", invalid="ignore"):
        _save(fig, "actiii_b")


# ========================================================================== #
#  PANEL (c): confirmatory FULL_STACK_CERT distribution (descriptive)         #
# ========================================================================== #
def panel_c():
    cert = _load_cert()
    anchors = [("nu200_b0.05", 200.0, 0.05), ("nu200_b0.6", 200.0, 0.60),
               ("nu2000_b0.05", 2000.0, 0.05), ("nu2000_b0.6", 2000.0, 0.60)]
    counts = {a[0]: {"COUNTEREXAMPLE": 0, "NUMERICAL_UNRESOLVED": 0,
                     "CERTIFIED": 0} for a in anchors}
    for r in cert:
        k = "nu%g_b%g" % (_fnum(r["nu"]), _fnum(r["b"]))
        counts[k][r["status"]] += 1
    ce_gaps = np.array([_fnum(r["primal_gap_lower_per_r"]) for r in cert
                        if r["status"] == "COUNTEREXAMPLE"
                        and np.isfinite(_fnum(r["primal_gap_lower_per_r"]))])

    fig, axs = plt.subplots(1, 2, figsize=(6.6, 3.0),
                            gridspec_kw={"width_ratios": [1.05, 1.0]})
    ax0, ax1 = axs
    labels = [r"$\nu$200" "\n" r"$b$0.05", r"$\nu$200" "\n" r"$b$0.60",
              r"$\nu$2000" "\n" r"$b$0.05", r"$\nu$2000" "\n" r"$b$0.60"]
    x = np.arange(4)
    ce = [counts[a[0]]["COUNTEREXAMPLE"] for a in anchors]
    un = [counts[a[0]]["NUMERICAL_UNRESOLVED"] for a in anchors]
    cc = [counts[a[0]]["CERTIFIED"] for a in anchors]
    ax0.bar(x, ce, color=ORANGE, label="COUNTEREXAMPLE", width=0.62)
    ax0.bar(x, un, bottom=ce, color=GREY, label="NUMERICAL_UNRESOLVED",
            width=0.62)
    ax0.bar(x, cc, bottom=np.array(ce) + np.array(un), color=GREEN,
            label="CERTIFIED", width=0.62)
    for xi, c_, u_ in zip(x, ce, un):
        ax0.text(xi, c_ / 2, str(c_), ha="center", va="center", color="white",
                 fontsize=8)
        ax0.text(xi, c_ + u_ / 2, str(u_), ha="center", va="center",
                 color="white", fontsize=8)
    ax0.set_xticks(x)
    ax0.set_xticklabels(labels, fontsize=7.5)
    ax0.set_ylabel("certificate cells (of 120 per anchor)")
    ax0.set_ylim(0, 128)
    ax0.set_title("status by anchor: 0/480 CERTIFIED", fontsize=9)
    ax0.legend(loc="upper center", bbox_to_anchor=(0.5, -0.16), ncol=1,
               frameon=False, fontsize=7.0, handlelength=1.2)

    # right: ECDF of finite COUNTEREXAMPLE primal gaps + threshold
    xs = np.sort(ce_gaps)
    ecdf = np.arange(1, xs.size + 1) / xs.size
    ax1.step(xs, ecdf, where="post", color=ORANGE, lw=1.8)
    ax1.axvline(1e-2, color=GREEN, ls="--", lw=1.2)
    ax1.annotate("near-optimality bar\n"
                 r"$G_{\rm stack}/r \leq 10^{-2}$",
                 xy=(1.05e-2, 0.5), xytext=(2.2e-2, 0.62), fontsize=7.2,
                 color=GREEN, ha="left", va="center",
                 arrowprops=dict(arrowstyle="->", color=GREEN, lw=0.8))
    ax1.set_xscale("log")
    ax1.set_xlim(5e-3, 3.0)
    ax1.set_ylim(0, 1.02)
    ax1.set_xlabel(r"primal gap / $r$  (COUNTEREXAMPLE cells)")
    ax1.set_ylabel("ECDF")
    ax1.set_title("all %d gaps exceed the bar\n(median %.2f)"
                  % (xs.size, float(np.median(xs))), fontsize=9)
    fig.suptitle("(c) FULL_STACK_CERT confirmatory distribution "
                 "(descriptive branch)", fontsize=9.5, y=1.0)
    fig.subplots_adjust(left=0.10, right=0.97, top=0.80, bottom=0.28,
                        wspace=0.32)
    _save(fig, "actiii_c")


# ========================================================================== #
#  PANEL (d): CENTREPIECE ridge-vs-0.60 fixed-dwell result                    #
# ========================================================================== #
D_NPZ = os.path.join(M1, "ACTIII_D_RECON.npz")
DISCLOSED = [("median", "m1_chirp_3"), ("max", "m1_maze_1"),
             ("min", "m1_contour_1")]


def _dot_dQ():
    """Per-image dQ (5-seed mean PSNR_rad, RIDGE-SCAT32 - SCAT32-060, nu=2000)
    grouped by family, from the imaging shards."""
    sys.path.insert(0, R63)
    sys.path.insert(0, os.path.dirname(R63))
    import m1_runner as m1
    acc = {}
    for p in sorted(glob.glob(os.path.join(SHARDS, "*.csv"))):
        if os.path.basename(p).startswith("M1_CERT"):
            continue
        for r in _read_cert_csv(p):     # generic csv (no overflow here)
            if _fnum(r["nu"]) != 2000.0:
                continue
            sid = r["shard_id"]
            arm = sid[len("M1_"):sid.rindex("_")]
            if arm in ("RIDGE-SCAT32", "SCAT32-060"):
                acc.setdefault((arm, r["image"]), []).append(
                    _fnum(r["PSNR_rad"]))
    out = {}
    imgs = sorted({img for (_a, img) in acc})
    for img in imgs:
        ri = acc.get(("RIDGE-SCAT32", img), [])
        qi = acc.get(("SCAT32-060", img), [])
        if len(ri) == 5 and len(qi) == 5:
            out[img] = (float(np.mean(ri)) - float(np.mean(qi)),
                        m1._family_of(img))
    return out


def panel_d():
    if not os.path.exists(D_NPZ):
        raise SystemExit(
            "panel (d) needs %s; run the recon precompute first "
            "(M1_FREEZE_LAUNCHED=1, ~10 s):\n  precompute_d_recon.py" % D_NPZ)
    z = np.load(D_NPZ, allow_pickle=True)
    dq = _dot_dQ()

    fig = plt.figure(figsize=(8.0, 5.4))
    gs = gridspec.GridSpec(
        3, 5, width_ratios=[1, 1, 1, 0.42, 1.55],
        height_ratios=[1, 1, 1], wspace=0.06, hspace=0.10,
        left=0.10, right=0.915, top=0.845, bottom=0.115)
    col_titles = ["ground truth", "SCAT32-060\n" r"($\bar\rho{=}0.60$)",
                  "RIDGE-SCAT32\n" r"($\bar\rho^\ast{\approx}22$)"]
    row_note = {"median": "median dQ", "max": "best (max dQ)",
                "min": "worst (min dQ)"}

    for ri, (tag, img) in enumerate(DISCLOSED):
        gt = z["%s__gt" % tag]
        vmax = float(np.percentile(gt, 99.7)) or float(gt.max()) or 1.0
        panels = [
            ("gt", gt, None),
            ("060", z["%s__SCAT32-060__recon" % tag],
             float(z["%s__SCAT32-060__psnr_rad" % tag])),
            ("ridge", z["%s__RIDGE-SCAT32__recon" % tag],
             float(z["%s__RIDGE-SCAT32__psnr_rad" % tag])),
        ]
        for ci, (kind, arr, psnr) in enumerate(panels):
            ax = fig.add_subplot(gs[ri, ci])
            ax.imshow(np.clip(arr, 0, vmax), cmap="gray", vmin=0, vmax=vmax,
                      interpolation="nearest")
            ax.set_xticks([])
            ax.set_yticks([])
            for s in ax.spines.values():
                s.set_linewidth(0.6)
            if ri == 0:
                ax.set_title(col_titles[ci], fontsize=8.5, pad=4)
            if psnr is not None:
                ax.text(0.04, 0.96, "%.1f dB" % psnr, transform=ax.transAxes,
                        fontsize=7.8, color="white", va="top", ha="left",
                        bbox=dict(boxstyle="round,pad=0.15", fc="black",
                                  ec="none", alpha=0.55))
            if ci == 0:
                ax.set_ylabel("%s\n%s" % (img.replace("m1_", ""),
                                          row_note[tag]), fontsize=8.2)
        # per-row dQ badge (green +, red -)
        axb = fig.add_subplot(gs[ri, 3])
        axb.axis("off")
        dqi = (float(z["%s__RIDGE-SCAT32__psnr_rad" % tag])
               - float(z["%s__SCAT32-060__psnr_rad" % tag]))
        col = GREEN if dqi >= 0 else RED
        axb.add_patch(FancyBboxPatch(
            (0.08, 0.30), 0.84, 0.40, transform=axb.transAxes,
            boxstyle="round,pad=0.02,rounding_size=0.08",
            fc=col, ec="none", alpha=0.92, clip_on=False))
        axb.text(0.5, 0.5, "%+.1f\ndB" % dqi, transform=axb.transAxes,
                 ha="center", va="center", color="white", fontsize=9,
                 fontweight="bold")

    # side strip: compact 24-point dQ dot plot grouped by family
    axs = fig.add_subplot(gs[:, 4])
    rng = np.random.default_rng(63)
    for fi, fam in enumerate(FAM_ORDER):
        ys = [v for img, (v, f) in dq.items() if f == fam]
        xs = fi + (rng.random(len(ys)) - 0.5) * 0.42
        axs.scatter(xs, ys, s=26, color=FAM_COLOR[fam],
                    edgecolor="white", linewidth=0.4, zorder=3)
    allv = np.array([v for v, _f in dq.values()])
    med = float(np.median(allv))
    n_pos = int((allv > 0).sum())
    axs.axhline(med, color="black", ls="-", lw=1.3, zorder=2)
    axs.axhline(1.0, color=GREEN, ls="--", lw=1.0, zorder=2)
    axs.axhline(0.0, color=GREY, ls=":", lw=1.0, zorder=1)
    trans = mtransforms.blended_transform_factory(axs.transAxes, axs.transData)
    bb = dict(boxstyle="round,pad=0.12", fc="white", ec="none", alpha=0.78)
    axs.text(0.03, med, "median %.2f dB" % med, transform=trans, fontsize=6.6,
             va="bottom", ha="left", color="black", bbox=bb, zorder=6)
    axs.text(0.03, 1.0, r"$\geq$1.0 dB bar", transform=trans, fontsize=6.6,
             va="top", ha="left", color=GREEN, bbox=bb, zorder=6)
    axs.set_xticks(range(6))
    axs.set_xticklabels(FAM_ORDER, rotation=40, ha="right", fontsize=7)
    axs.set_ylabel("per-image dQ (dB)", fontsize=8.4)
    axs.yaxis.tick_right()
    axs.yaxis.set_label_position("right")
    axs.set_xlim(-0.7, 5.7)
    axs.set_title(r"24-image dQ ($%d/24{>}0$)" % n_pos, fontsize=8.2, pad=4)

    fig.suptitle(r"(d) Ridge power knob sharpens detail at fixed dwell "
                 r"($\nu{=}2000$, seed 0)", fontsize=10.5, y=0.965)
    _save(fig, "actiii_d")


# ========================================================================== #
#  PANEL (e): resource-corner schematic (conjugate-corners doctrine)          #
# ========================================================================== #
def _check(ax, x, y, s, color):
    ax.plot([x - 0.9 * s, x - 0.15 * s], [y, y - 0.7 * s], color=color,
            lw=2.4, solid_capstyle="round", zorder=6)
    ax.plot([x - 0.15 * s, x + s], [y - 0.7 * s, y + 0.9 * s], color=color,
            lw=2.4, solid_capstyle="round", zorder=6)


def _cross(ax, x, y, s, color):
    ax.plot([x - s, x + s], [y - s, y + s], color=color, lw=2.4,
            solid_capstyle="round", zorder=6)
    ax.plot([x - s, x + s], [y + s, y - s], color=color, lw=2.4,
            solid_capstyle="round", zorder=6)


def panel_e():
    fig, ax = plt.subplots(figsize=(5.4, 4.2))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.axis("off")

    # two conjugate corner regions on a power x time map
    ax.add_patch(Rectangle((0.6, 5.2), 4.4, 4.2, fc=BLUE, ec="none",
                           alpha=0.10))
    ax.add_patch(Rectangle((5.0, 0.6), 4.4, 4.2, fc=ORANGE, ec="none",
                           alpha=0.12))
    ax.plot([0.6, 9.4], [9.4, 0.6], color=GREY, ls="--", lw=1.0)

    # axes arrows
    ax.add_patch(FancyArrowPatch((0.6, 0.6), (9.6, 0.6),
                                 arrowstyle="-|>", mutation_scale=13,
                                 color="black", lw=1.1))
    ax.add_patch(FancyArrowPatch((0.6, 0.6), (0.6, 9.6),
                                 arrowstyle="-|>", mutation_scale=13,
                                 color="black", lw=1.1))
    ax.text(9.6, 0.2, "optical power / flux budget", ha="right", fontsize=8.5)
    ax.text(0.2, 9.6, "acquisition-time budget", rotation=90, va="top",
            fontsize=8.5)

    # corner 1: photon-budgeted (low power, high time)
    ax.text(2.8, 8.9, "Photon-budgeted corner", ha="center", fontsize=9.2,
            fontweight="bold", color=BLUE)
    ax.text(2.8, 8.3, "(Q90 count-time secondary)", ha="center", fontsize=7.6,
            color=BLUE)
    ax.plot([2.1], [7.55], "o", color=BLUE, ms=11, zorder=5)
    ax.text(2.1, 6.98, "SCAT32-SAFE comparator",
            ha="center", va="top", fontsize=7.6)
    # badge: corrected elapsed-time speed verdict
    ax.add_patch(FancyBboxPatch((0.9, 5.35), 3.9, 0.72,
                 boxstyle="round,pad=0.03,rounding_size=0.10", fc="white",
                 ec=RED, lw=1.3, zorder=5))
    _check(ax, 1.35, 5.71, 0.16, GREEN)
    ax.text(1.75, 5.71, "elapsed T_opt speed = PASS", va="center", fontsize=8,
            color=GREEN, fontweight="bold", zorder=6)

    # corner 2: time-limited, power-available (high power, low time)
    ax.text(7.2, 4.55, "Time-limited, power-available", ha="center",
            fontsize=9.2, fontweight="bold", color=ORANGE)
    ax.text(7.2, 4.0, "(fixed-dwell quality primary)", ha="center",
            fontsize=7.6, color=ORANGE)
    ax.plot([8.0], [2.7], "o", color=ORANGE, ms=11, zorder=5)
    ax.text(8.0, 2.12, r"ridge point $\bar\rho^\ast$: +1.87 dB median",
            ha="center", va="top", fontsize=7.6)
    # badge: RIDGE_OPERATING_PASS = TRUE
    ax.add_patch(FancyBboxPatch((5.1, 0.7), 4.2, 0.72,
                 boxstyle="round,pad=0.03,rounding_size=0.10", fc="white",
                 ec=GREEN, lw=1.3, zorder=5))
    _check(ax, 5.55, 1.06, 0.16, GREEN)
    ax.text(5.95, 1.06, "RIDGE_OPERATING_PASS = TRUE", va="center",
            fontsize=8, color=GREEN, fontweight="bold", zorder=6)

    # the global power knob moves the operating point between corners
    ax.add_patch(FancyArrowPatch((2.6, 6.7), (7.4, 2.9),
                 connectionstyle="arc3,rad=-0.25", arrowstyle="-|>",
                 mutation_scale=15, color="black", lw=1.4))
    ax.text(5.0, 5.55, "global power knob", ha="center", fontsize=8,
            style="italic", rotation=-27)

    ax.set_title("(e) Conjugate-corners doctrine: one knob, two regimes",
                 fontsize=9.6)
    fig.subplots_adjust(left=0.02, right=0.98, top=0.92, bottom=0.02)
    _save(fig, "actiii_e")


# ========================================================================== #
#  HERO mechanism figure                                                      #
# ========================================================================== #
RHO_CURVE_MAX = 30.0     # frozen exact-PMF evaluation is smooth to here for
                         # BOTH anchors (nu=200 finite-difference noise sets in
                         # near the count ceiling at rho ~ 31; nu=2000 later)


def _ridge_curve_exact(nu, rho_lo=0.3, rho_hi=RHO_CURVE_MAX, n=130):
    """Dense (rho, J) from the FROZEN exact count-law machinery
    (code/round63/physics.fisher_exact), information about log-lambda per
    unit time in tau units — same definition as fisher_ridge.py. Evaluated
    densely instead of reading the coarse 49-point cache, whose nu=200 tail
    (rho >= 44) carries a visible finite-difference artifact."""
    sys.path.insert(0, R63)
    from physics import fisher_exact
    T = float(nu)
    rho = np.geomspace(rho_lo, rho_hi, n)
    with np.errstate(all="ignore"):
        ie = np.array([fisher_exact(r, T, 1.0) * r ** 2 / T for r in rho])
    return rho, ie


def _mech_scene_insets():
    """(scene, recon) 32x32 arrays for the pipeline object/recon boxes: the
    m1_maze_1 confirmatory scene and its RIDGE-SCAT32 seed-0 reconstruction
    from the panel-(d) cache; deterministic synthetic fallback if absent."""
    if os.path.exists(D_NPZ):
        z = np.load(D_NPZ, allow_pickle=True)
        return z["max__gt"], z["max__RIDGE-SCAT32__recon"]
    rng = np.random.default_rng(1)                      # fallback (display)
    s = (rng.random((32, 32)) < 0.15).astype(float)
    return s, s + 0.05 * rng.standard_normal((32, 32))


BOXEC = "#33475b"
BOXFC = "#eef2f6"


def fig_mechanism():
    fig = plt.figure(figsize=(9.4, 4.4))
    gs = gridspec.GridSpec(1, 2, width_ratios=[1.72, 1.0], wspace=0.22,
                           left=0.012, right=0.955, top=0.90, bottom=0.10)
    axm = fig.add_subplot(gs[0, 0])
    axm.set_xlim(0, 100)
    axm.set_ylim(0, 52)
    axm.axis("off")

    def rbox(x, y, w, h, fc=BOXFC, ec=BOXEC, lw=1.2):
        axm.add_patch(FancyBboxPatch(
            (x, y), w, h, boxstyle="round,pad=0.3,rounding_size=1.4",
            fc=fc, ec=ec, lw=lw, zorder=2))

    def beam(x0, x1, y, color=ORANGE, lw=2.2):
        axm.add_patch(FancyArrowPatch((x0, y), (x1, y), arrowstyle="-|>",
                      mutation_scale=12, color=color, lw=lw, zorder=3,
                      shrinkA=0, shrinkB=0))

    def label_below(cx, ytop, txt):
        axm.text(cx, ytop, txt, ha="center", va="top", fontsize=7.8,
                 color="black")

    def img_inset(cx, cy, side, arr, ec, title=None, vmax=None):
        """Square image inset centred at data (cx, cy), side in x-data units
        (height converted through the axes display aspect)."""
        pos = axm.get_position()
        fw, fh = fig.get_size_inches()
        disp_aspect = (pos.width * fw) / (pos.height * fh)
        w = side
        h = side * (52.0 / 100.0) * disp_aspect
        iax = axm.inset_axes([(cx - w / 2) / 100.0, (cy - h / 2) / 52.0,
                              w / 100.0, h / 52.0])
        vm = vmax if vmax is not None else (float(np.percentile(arr, 99.7))
                                            or 1.0)
        iax.imshow(np.clip(arr, 0, vm), cmap="gray", vmin=0, vmax=vm,
                   interpolation="nearest")
        iax.set_xticks([])
        iax.set_yticks([])
        for s in iax.spines.values():
            s.set_edgecolor(ec)
            s.set_linewidth(1.1)
        if title:
            iax.set_title(title, fontsize=6.4, color=ec, pad=1.5)
        return iax

    # ---- pipeline chain (labels BELOW boxes, paper-1 language) ------------ #
    yb, bh = 30, 12                       # box bottom / height
    yc = yb + bh / 2                      # beam height
    scene, recon = _mech_scene_insets()

    # 1) laser source: orange beam inside, GLOBAL POWER KNOB dial on top
    rbox(2, yb, 13, bh)
    beam(4.0, 13.0, yc)
    label_below(8.5, yb - 1.2, "laser source")
    # ---- the protagonist: power dial (circle + ticks + needle + halo) ----- #
    from matplotlib.patches import Ellipse
    pos = axm.get_position()
    fw, fh = fig.get_size_inches()
    kx2y = (52.0 / 100.0) * (pos.width * fw) / (pos.height * fh)
    dcx, dcy, dr = 8.5, 45.5, 4.6

    def dial_xy(r_frac, ang_deg):
        a = np.deg2rad(ang_deg)
        return (dcx + dr * r_frac * np.cos(a),
                dcy + dr * r_frac * kx2y * np.sin(a))

    axm.add_patch(Ellipse((dcx, dcy), 2 * (dr + 1.7),
                          2 * (dr + 1.7) * kx2y, fc=GREEN, ec="none",
                          alpha=0.16, zorder=3))                 # green halo
    axm.add_patch(Ellipse((dcx, dcy), 2 * dr, 2 * dr * kx2y, fc="white",
                          ec=GREEN, lw=2.0, zorder=4))
    for ang in np.linspace(215, -35, 9):                         # tick marks
        x0, y0 = dial_xy(0.78, ang)
        x1, y1 = dial_xy(0.95, ang)
        axm.plot([x0, x1], [y0, y1], color=GREEN, lw=1.1, zorder=5,
                 solid_capstyle="round")
    axm.add_patch(FancyArrowPatch((dcx, dcy), dial_xy(0.70, 33),
                  arrowstyle="-|>", mutation_scale=10, color=GREEN, lw=2.3,
                  zorder=6))                                     # needle
    axm.plot([dcx], [dcy], "o", color=GREEN, ms=3.5, zorder=6)
    axm.text(dcx + dr + 3.2, dcy + 3.0, "GLOBAL POWER KNOB",
             fontsize=9.2, color=GREEN, fontweight="bold", va="center",
             ha="left", zorder=6)
    axm.text(dcx + dr + 3.2, dcy - 0.4,
             r"$\Phi$: one scalar source multiplier"
             "\n" r"sets the load $\bar\rho = \tau\,\mathbb{E}[\lambda]$",
             fontsize=6.8, color=GREEN, va="center", ha="left", zorder=6)
    axm.plot([dcx, dcx], [yb + bh, dcy - (dr + 1.0) * kx2y - 1.0],
             color=GREEN, lw=1.4, zorder=3)       # dial stem onto the source

    beam(15.4, 21.6, yc)                                         # LS -> DMD

    # 2) DMD box with the SCAT32 pattern inside
    rbox(22, yb, 13, bh)
    rng = np.random.default_rng(3232)
    pat = (rng.random((32, 32)) < 0.5).astype(float)
    img_inset(28.5, yc, 7.6, pat, BLUE)
    label_below(28.5, yb - 1.2, "DMD, SCAT32 $a_i$")
    beam(35.4, 41.6, yc)                                         # DMD -> obj

    # 3) object box with the confirmatory maze scene inside
    rbox(42, yb, 13, bh)
    img_inset(48.5, yc, 7.6, scene, BOXEC)
    label_below(48.5, yb - 1.2, "object $x$")
    beam(55.4, 61.6, yc)                                         # obj -> SPD

    # 4) SPD box with a bowtie lens + sensor icon
    rbox(62, yb, 13, bh)
    axm.fill([64.5, 68.5, 64.5], [yc - 2.6, yc, yc + 2.6], color=SKY,
             alpha=0.9, zorder=3)
    axm.fill([72.0, 68.5, 72.0], [yc - 1.4, yc, yc + 1.4], color=SKY,
             alpha=0.9, zorder=3)
    axm.add_patch(Ellipse((72.6, yc), 2.2, 1.4, fc="black", zorder=4))
    label_below(68.5, yb - 1.2, "SPD photon-counting")
    # blue counts path SPD -> recon
    beam(75.4, 84.6, yc, color=BLUE, lw=2.2)
    axm.text(80.0, yc + 2.0, "bucket\ncounts $N_i$", ha="center",
             va="bottom", fontsize=6.6, color=BLUE)

    # 5) reconstruction box (green, like the paper-1 RQL box) with the
    #    RIDGE-SCAT32 maze reconstruction inside
    rbox(85, yb, 13, bh, fc="#EAF7F2", ec=GREEN)
    vm = float(np.percentile(scene, 99.7)) or 1.0
    img_inset(91.5, yc, 7.6, recon, GREEN, vmax=vm)
    label_below(91.5, yb - 1.2, "RQL recon. $\\hat{x}$")

    # ---- dead-time timeline inset (enlarged, legend attached below) ------- #
    axm.text(68.5, yb - 5.0, r"dead time $\tau$  $\rightarrow$ timeline",
             fontsize=6.6, color=ORANGE, ha="center", va="center")
    axm.add_patch(FancyArrowPatch((62.5, yb - 5.0), (54.0, 20.6),
                  arrowstyle="-|>", mutation_scale=8, color=ORANGE, lw=1.1,
                  ls=":", zorder=3))
    axt = axm.inset_axes([0.06, 0.035, 0.47, 0.355])
    axt.set_xlim(0, 10)
    axt.set_ylim(-1.05, 3.2)
    axt.axis("off")
    axt.set_title("photon arrivals censored by dead time", fontsize=7.4,
                  color=BOXEC, pad=2)
    axt.plot([0.2, 9.8], [0.0, 0.0], color="black", lw=1.1)
    axt.text(9.8, 2.62, r"exposure $T=\nu\tau$", fontsize=6.8, ha="right",
             color=BOXEC)
    arrivals = [0.9, 1.5, 2.9, 3.35, 3.8, 5.3, 6.9, 7.4, 8.7]
    ready, tau_w = 0.0, 0.85
    first_hold = None
    for i, t in enumerate(arrivals):
        jit = (i == 5)                        # one jitter-broadened hold
        w = tau_w * (1.55 if jit else 1.0)
        if t >= ready:                        # recorded count
            axt.add_patch(Rectangle((t, 0.0), w, 1.55, fc=ORANGE, ec="none",
                          alpha=0.38 if jit else 0.16, zorder=2))
            axt.plot([t, t], [0.0, 1.55], color=GREEN, lw=1.8, zorder=4,
                     solid_capstyle="round")
            axt.plot([t], [1.55], marker="v", color=GREEN, ms=4.5, zorder=4)
            if first_hold is None:
                first_hold = (t, w)
            if jit:
                axt.text(t + w / 2, 1.78, "jitter", fontsize=6.2,
                         color=ORANGE, ha="center")
            ready = t + w
        else:                                 # lost inside the blind interval
            axt.plot([t], [0.78], marker="x", color=ORANGE, ms=6.0, mew=1.7,
                     zorder=5)
    # big orange tau glyph over the first hold (paper-1 mathtext form);
    # ruler = line + end ticks (an arrowed span collapses at this width)
    t0, w0 = first_hold
    axt.plot([t0, t0 + w0], [2.10, 2.10], color=BOXEC, lw=1.0)
    for xe in (t0, t0 + w0):
        axt.plot([xe, xe], [1.94, 2.26], color=BOXEC, lw=1.0)
    axt.text(t0 + w0 / 2, 2.34, r"$\tau$", fontsize=14.0, color=ORANGE,
             ha="center", va="bottom", clip_on=False)
    # legend ATTACHED BELOW the timeline (two rows, no overlap)
    axt.text(0.2, -0.42, r"$\blacktriangledown$ recorded count",
             color=GREEN, fontsize=6.4, ha="left", va="center")
    axt.text(9.8, -0.42, r"$\times$ lost (blind)", color=ORANGE,
             fontsize=6.4, ha="right", va="center")
    axt.text(0.2, -0.85, r"shaded: $\tau$ hold (darker: jitter-broadened)",
             color=ORANGE, fontsize=6.4, ha="left", va="center")

    axm.set_title("(a) Dead-time-aware single-pixel imaging pipeline",
                  fontsize=9.4, loc="left")

    # ---- right: count-information ridge law (dense exact evaluation) ------ #
    axr = fig.add_subplot(gs[0, 1])
    rj_json = json.load(open(os.path.join(
        REPO, "results", "round63_theory", "fisher_ridge.json")))["ridge"]
    for nu, col in ((2000, BLUE), (200, ORANGE)):
        rho, ie = _ridge_curve_exact(nu)
        axr.plot(rho, ie, color=col, lw=1.9, label=r"$\nu=%d$" % nu,
                 solid_capstyle="round")
        rs = float(rj_json[str(nu)]["rho_star"])       # frozen ridge values
        axr.axvline(rs, color=col, ls="--", lw=1.0, alpha=0.8)
        i_at = float(np.interp(rs, rho, ie))
        axr.plot([rs], [i_at], "o", color=col, ms=6, zorder=5)
        axr.annotate(r"$\bar\rho^\ast{=}%.1f$" % rs, xy=(rs, i_at),
                     xytext=(rs * 0.60, i_at - 0.14), fontsize=7.4, color=col)
        print("[mech] nu=%d: dense J on [%.2f, %.2f] (%d pts), "
              "rho*=%.1f (frozen)" % (nu, rho[0], rho[-1], rho.size, rs),
              flush=True)
    axr.set_xscale("log")
    axr.set_xlim(0.3, 32)
    axr.set_ylim(0, 1.05)
    axr.set_xlabel(r"detector load  $\bar\rho = \tau\,\mathbb{E}[\lambda]$")
    axr.set_ylabel(r"count-information efficiency  $J(\bar\rho;\nu)$")
    axr.set_title(r"(b) Ridge law $\bar\rho^\ast(\nu)=(6\nu)^{1/3}-2/3$",
                  fontsize=9.4)
    axr.text(0.03, 0.975, r"zero-jitter limit ($c=0$)",
             transform=axr.transAxes, fontsize=6.8, color=GREY,
             va="top", ha="left")
    # operating-map knob arrow toward the ridge
    axr.annotate("", xy=(18, 0.30), xytext=(1.1, 0.30),
                 arrowprops=dict(arrowstyle="-|>", color=GREEN, lw=1.8))
    axr.text(1.25, 0.345, "global power knob", fontsize=7.4, color=GREEN,
             fontweight="bold")
    axr.legend(loc="lower right", frameon=False, fontsize=8)
    _save(fig, "fig_mechanism")


# ========================================================================== #
def main(argv=None):
    setup_style()
    which = [a.lower() for a in (argv or sys.argv[1:])]
    todo = {
        "a": panel_a, "b": panel_b, "c": panel_c, "d": panel_d,
        "e": panel_e, "m": fig_mechanism, "mech": fig_mechanism,
    }
    if not which:
        which = ["b", "c", "d", "e", "m", "a"]   # a last (needs precompute)
    for w in which:
        fn = todo.get(w)
        if fn is None:
            print("[figs] unknown panel '%s'" % w, flush=True)
            continue
        try:
            fn()
        except SystemExit as e:
            print("[figs] SKIP %s: %s" % (w, e), flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
