"""SUPPLEMENT S7 -- S2B/S2C ensemble and undersampling sensitivity.

Sources of record:
  * results/round63_s2_s2b/pilot_rows.csv -- dense Bernoulli(1/2) at two
    sampling budgets M in {1024, 2048} (undersampling sensitivity);
  * results/round63_s2_s2c/pilot_rows.csv -- complementary Hadamard-type pairs
    (hadpair) and gamma-modulated patterns (gam4) at M=2048 (ensemble
    sensitivity).

Reports median radiometric PSNR for the RQL arm per (M or pattern, rho, nu) over
nu in {100, 500, 2000} and rho in {0.05, 0.6, 1.0}.

Writes paper/supp_tables/S7_ensemble.tex.
"""
import os
import sys
import statistics
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from supp_common import REPO, to_float, load_csv, fnum, tex_escape, git_commit, write_fragment  # noqa: E402

S2B = os.path.join(REPO, "results", "round63_s2_s2b", "pilot_rows.csv")
S2C = os.path.join(REPO, "results", "round63_s2_s2c", "pilot_rows.csv")
RHOS = [0.05, 0.6, 1.0]
NUS = [100.0, 500.0, 2000.0]


def medians(path, group_col):
    """(group_value, rho, nu) -> (median PSNR_rad, n) for RQL rows."""
    rows = load_csv(path)
    by = defaultdict(list)
    for r in rows:
        if r["arm"] != "RQL":
            continue
        if to_float(r["nu"]) not in NUS or to_float(r["rho_bar"]) not in RHOS:
            continue
        v = to_float(r["PSNR_rad"])
        if v is None:
            continue
        by[(r[group_col], to_float(r["rho_bar"]), to_float(r["nu"]))].append(v)
    return {k: (statistics.median(vs), len(vs)) for k, vs in by.items()}


def emit(L, title, med, groups, group_fmt, label, caption):
    L.append(r"\begin{table}[t]")
    L.append(r"\centering")
    L.append(r"\caption{%s}" % caption)
    L.append(r"\label{%s}" % label)
    L.append(r"\begin{tabular}{ll" + "r" * len(NUS) + "}")
    L.append(r"\toprule")
    L.append(r"%s & $\bar\rho$ & " % title +
             " & ".join(r"$\nu{=}%d$" % int(nu) for nu in NUS) + r" \\")
    L.append(r"\midrule")
    for gi, g in enumerate(groups):
        for ri, rho in enumerate(RHOS):
            lab = group_fmt(g) if ri == 0 else ""
            cells = []
            for nu in NUS:
                mv = med.get((str(g), rho, nu)) or med.get((g, rho, nu))
                cells.append(fnum(mv[0], 2) if mv else "--")
            L.append("%s & %s & %s \\\\" % (lab, fnum(rho, 2), " & ".join(cells)))
        if gi != len(groups) - 1:
            L.append(r"\midrule")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")


def main():
    cb, cc = git_commit(S2B), git_commit(S2C)
    med_b = medians(S2B, "M")
    med_c = medians(S2C, "pattern")
    print("[S7] S2B source=%s (commit %s)  S2C source=%s (commit %s)" % (S2B, cb, S2C, cc))
    print("[S7] S2B median PSNR_rad (RQL) by (M,rho,nu):")
    for M in ["1024", "2048"]:
        for rho in RHOS:
            print("[S7]   M=%s rho=%.2f : %s" % (M, rho,
                  " ".join("%s" % (fnum(med_b[(M, rho, nu)][0], 2) if (M, rho, nu) in med_b else "--") for nu in NUS)))
    print("[S7] S2C median PSNR_rad (RQL) by (pattern,rho,nu):")
    for pat in ["hadpair", "gam4"]:
        for rho in RHOS:
            print("[S7]   %s rho=%.2f : %s" % (pat, rho,
                  " ".join("%s" % (fnum(med_c[(pat, rho, nu)][0], 2) if (pat, rho, nu) in med_c else "--") for nu in NUS)))

    L = []
    L.append(r"%% S7: S2B/S2C ensemble and undersampling sensitivity")
    L.append(r"%% GENERATED by code/round63/figs/supp_s7_ensemble.py -- do not edit by hand")
    L.append(r"%% sources: s2_s2b/pilot_rows.csv (%s), s2_s2c/pilot_rows.csv (%s)" % (cb, cc))
    emit(L, "$M$", med_b, ["1024", "2048"], lambda g: r"\multirow{3}{*}{%s}" % g,
         "tab:s7_s2b",
         "Undersampling sensitivity (S2B): median RQL radiometric PSNR (dB) for "
         "dense Bernoulli$(1/2)$ illumination at two sampling budgets "
         "$M\\in\\{1024,2048\\}$, over 12 scenes $\\times$ 3 seeds per cell. "
         "Source: \\texttt{round63\\_s2\\_s2b/pilot\\_rows.csv} (commit %s)." % cb)
    emit(L, "pattern", med_c, ["hadpair", "gam4"],
         lambda g: r"\multirow{3}{*}{\texttt{%s}}" % tex_escape(g),
         "tab:s7_s2c",
         "Ensemble sensitivity (S2C): median RQL radiometric PSNR (dB) for "
         "complementary Hadamard-type pairs (\\texttt{hadpair}) and gamma-modulated "
         "patterns (\\texttt{gam4}) at $M=2048$, over 12 scenes $\\times$ 3 seeds per "
         "cell. Source: \\texttt{round63\\_s2\\_s2c/pilot\\_rows.csv} (commit %s)." % cc)
    write_fragment("S7_ensemble.tex", L)
    return 0


if __name__ == "__main__":
    sys.exit(main())
