"""SUPPLEMENT S6 -- dynamic-scattering detail.

Source of record: results/round63_study2/scattering_rows.csv (multiplicative
lognormal AR(1) dynamic scattering, CV(alpha)=0.20, applied before dead time;
k=16 geometry, six frozen mechanism representatives, RQL). Reports, per
(rho_bar, nu), the mean and sample sd of radiometric PSNR and the per-nu
high-flux gain (fast mean minus safe mean).

Established gains reproduced: +0.66 / +1.84 / +2.32 dB at nu = 20 / 200 / 2000.

Writes paper/supp_tables/S6_scattering.tex.
"""
import os
import sys
import statistics
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from supp_common import REPO, to_float, load_csv, fnum, git_commit, write_fragment  # noqa: E402

SRC = os.path.join(REPO, "results", "round63_study2", "scattering_rows.csv")
NUS = [20.0, 200.0, 2000.0]
RHOS = [0.05, 0.6]


def stats_of(vals):
    return (statistics.mean(vals), statistics.stdev(vals) if len(vals) >= 2 else float("nan"), len(vals))


def main():
    rows = load_csv(SRC)
    commit = git_commit(SRC)
    acv = sorted(set(r["alpha_cv"] for r in rows))
    by = defaultdict(list)     # (rho, nu) -> [PSNR_rad]
    for r in rows:
        if r["arm"] != "RQL":
            continue
        v = to_float(r["PSNR_rad"])
        if v is None:
            continue
        by[(to_float(r["rho_bar"]), to_float(r["nu"]))].append(v)

    print("[S6] source = %s (commit %s) alpha_cv=%s" % (SRC, commit, acv))
    cell = {}
    for rho in RHOS:
        for nu in NUS:
            cell[(rho, nu)] = stats_of(by[(rho, nu)])
    for nu in NUS:
        m_s, sd_s, n_s = cell[(0.05, nu)]
        m_f, sd_f, n_f = cell[(0.6, nu)]
        print("[S6]  nu=%5d safe=%.3f+/-%.3f (n=%d) fast=%.3f+/-%.3f (n=%d) gain=%+.3f"
              % (int(nu), m_s, sd_s, n_s, m_f, sd_f, n_f, m_f - m_s))

    L = []
    L.append(r"%% S6: dynamic-scattering per-(rho,nu) means + sd")
    L.append(r"%% GENERATED by code/round63/figs/supp_s6_scattering.py -- do not edit by hand")
    L.append(r"%% source: results/round63_study2/scattering_rows.csv (commit %s)" % commit)
    L.append(r"\begin{table}[t]")
    L.append(r"\centering")
    L.append(r"\caption{Dynamic-scattering detail: RQL radiometric PSNR under "
             r"multiplicative lognormal AR(1) scattering "
             r"($\mathrm{CV}(\alpha)=0.20$, applied before dead time) on the $k=16$ "
             r"geometry over the six frozen mechanism representatives. Entries are "
             r"mean $\pm$ sample sd (dB) over the six scenes $\times$ three seeds; the "
             r"gain column is the fast-minus-safe difference of means. The high-flux "
             r"gain persists and grows with dwell.}")
    L.append(r"\label{tab:s6_scattering}")
    L.append(r"\begin{tabular}{rccr}")
    L.append(r"\toprule")
    L.append(r"$\nu$ & safe ($\bar\rho{=}0.05$) & fast ($\bar\rho{=}0.6$) & gain (dB) \\")
    L.append(r"\midrule")
    for nu in NUS:
        m_s, sd_s, _ = cell[(0.05, nu)]
        m_f, sd_f, _ = cell[(0.6, nu)]
        L.append(r"%d & $%s \pm %s$ & $%s \pm %s$ & %s \\" % (
            int(nu), fnum(m_s, 2), fnum(sd_s, 2), fnum(m_f, 2), fnum(sd_f, 2),
            fnum(m_f - m_s, 2, plus=True)))
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")
    write_fragment("S6_scattering.tex", L)
    return 0


if __name__ == "__main__":
    sys.exit(main())
