"""SUPPLEMENT S5 -- no-gate occupancy-ladder per-image fixed-dwell tables.

Per-image fixed-dwell high-flux gain (per-image seed-mean radiometric PSNR at
rho_bar=0.6 minus rho_bar=0.05, both at nu=2000) on every rung of the frozen
occupancy ladder:

  * k=512 (dense, 50%)   -- results/round63_study2/controls_rows.csv
  * k=32  (3.1%)         -- results/round63_study2/robustness_rows.csv
  * k=16  (1.6%, gated)  -- results/round63_study2/study2_summary.json
                            (the DeltaQ_budget field == raw seed-mean fast-safe)
  * k=1   (raster, 0.1%) -- results/round63_study2/controls_rows.csv

Established cohort medians reproduced by this script: +0.64 / +4.13 / +1.16 /
+3.56 dB at k = 512 / 32 / 16 / 1.

Writes paper/supp_tables/S5_ladder.tex.
"""
import os
import sys
import json
import statistics
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from supp_common import REPO, to_float, load_csv, tt, fnum, git_commit, write_fragment  # noqa: E402

R63 = os.path.join(REPO, "results", "round63_study2")
CONTROLS = os.path.join(R63, "controls_rows.csv")
ROBUST = os.path.join(R63, "robustness_rows.csv")
SUMMARY = os.path.join(R63, "study2_summary.json")
NU = 2000.0


def csv_deltas(path, k):
    """image -> (seed-mean PSNR_rad fast(0.6) - safe(0.05)) at nu=2000, RQL, occupancy k."""
    rows = load_csv(path)
    by = defaultdict(lambda: defaultdict(list))   # image -> rho -> [vals]
    for r in rows:
        if r["arm"] != "RQL":
            continue
        if to_float(r["nu"]) != NU or int(to_float(r["k"])) != k:
            continue
        v = to_float(r["PSNR_rad"])
        if v is None:
            continue
        by[r["image"]][to_float(r["rho_bar"])].append(v)
    out = {}
    for img, d in by.items():
        if 0.05 in d and 0.6 in d:
            out[img] = statistics.mean(d[0.6]) - statistics.mean(d[0.05])
    return out


def main():
    d512 = csv_deltas(CONTROLS, 512)
    d32 = csv_deltas(ROBUST, 32)
    d1 = csv_deltas(CONTROLS, 1)
    js = json.load(open(SUMMARY, encoding="utf-8"))
    per = js["endpoint_analysis"]["per_image"]
    order = [(p["image"], p["family"]) for p in per]
    d16 = {p["image"]: p["DeltaQ_budget"] for p in per}

    cols = [(512, d512, git_commit(CONTROLS)),
            (32, d32, git_commit(ROBUST)),
            (16, d16, git_commit(SUMMARY)),
            (1, d1, git_commit(CONTROLS))]

    print("[S5] per-image fixed-dwell delta (fast-safe PSNR_rad, nu=2000, RQL)")
    for k, d, c in cols:
        vals = list(d.values())
        vals.sort()
        npos = sum(1 for x in vals if x > 0)
        print("[S5]  k=%3d (commit %s): n=%d median=%s pos=%d/%d" %
              (k, c, len(vals), fnum(statistics.median(vals), 4, plus=True), npos, len(vals)))

    L = []
    L.append(r"%% S5: no-gate occupancy-ladder per-image fixed-dwell gain")
    L.append(r"%% GENERATED by code/round63/figs/supp_s5_ladder.py -- do not edit by hand")
    L.append(r"%% sources: controls_rows.csv (%s), robustness_rows.csv (%s), "
             r"study2_summary.json (%s)" %
             (git_commit(CONTROLS), git_commit(ROBUST), git_commit(SUMMARY)))
    L.append(r"\begin{table}[t]")
    L.append(r"\centering")
    L.append(r"{\footnotesize")
    L.append(r"\setlength{\tabcolsep}{6pt}")
    L.append(r"\caption{No-gate occupancy-ladder per-image fixed-dwell high-flux gain "
             r"(per-image seed-mean radiometric PSNR at $\bar\rho=0.6$ minus "
             r"$\bar\rho=0.05$, both at $\nu=2000$, equal mean detector load and equal "
             r"incident dose across occupancies). $k=16$ is the gate-carrying arm "
             r"(values are the frozen $\Delta Q_{\mathrm{budget}}$); $k=512/32/1$ are "
             r"no-gate controls/robustness rungs. The profile is nonmonotone in "
             r"sparsity: $k=32$ attains the largest median gain, combining most of the "
             r"contrast benefit with half the conditioning burden of $k=16$.}")
    L.append(r"\label{tab:s5_ladder}")
    L.append(r"\begin{tabular}{llrrrr}")
    L.append(r"\toprule")
    L.append(r" & & \multicolumn{4}{c}{$\Delta$PSNR (dB) by occupancy $k$}\\")
    L.append(r"\cmidrule(lr){3-6}")
    L.append(r"image & family & $k{=}512$ & $k{=}32$ & $k{=}16$ & $k{=}1$ \\")
    L.append(r"  & & (50\%) & (3.1\%) & (1.6\%) & (0.1\%) \\")
    L.append(r"\midrule")
    for img, fam in order:
        cells = [fnum(d.get(img), 2, plus=True) for k, d, c in cols]
        L.append("%s & %s & %s \\\\" % (tt(img), fam, " & ".join(cells)))
    L.append(r"\midrule")
    med = []
    pos = []
    for k, d, c in cols:
        vals = [d[img] for img, fam in order if img in d]
        med.append(fnum(statistics.median(vals), 2, plus=True))
        pos.append("%d/%d" % (sum(1 for x in vals if x > 0), len(vals)))
    L.append(r"\textbf{median} & & " + " & ".join(r"\textbf{%s}" % m for m in med) + r" \\")
    L.append(r"scenes $>0$ & & " + " & ".join(pos) + r" \\")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"}")
    L.append(r"\end{table}")
    write_fragment("S5_ladder.tex", L)
    return 0


if __name__ == "__main__":
    sys.exit(main())
