"""SUPPLEMENT S2 -- full NATURAL-30 cohort per-image endpoint table.

Source of record: results/round63_s2_natural/PILOT_SUMMARY.md, section
"1. Acquisition-speed endpoint S_gate -- RQL". The frozen analyzer markdown
table is parsed verbatim (the trailing '**median S_gate**' summary row is
dropped and the median is re-reported in the caption). Reproduced as a
longtable; the two synthetic stress images (low_contrast, fine_lines) are
flagged in the caption via their DeltaQ_budget entries.

Writes paper/supp_tables/S2_natural.tex.
"""
import os
import sys
import statistics

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from supp_common import REPO, tex_escape, tt, fnum, git_commit, find_table, write_fragment  # noqa: E402

SRC = os.path.join(REPO, "results", "round63_s2_natural", "PILOT_SUMMARY.md")

# short status labels so the longtable fits \textwidth; full label given in caption
STATUS_SHORT = {
    "NORMAL": "NORMAL",
    "SAFE_RANGE_UNINFORMATIVE": "SRU",
    "FAST_LEFT_CENSORED": "FLC",
    "BOTH_LEFT_CENSORED": "BLC",
    "SAFE_LEFT_FAST_INTERIOR": "SLFI",
    "FAST_RIGHT_CENSORED": "FRC",
    "ANALYSIS_FAILURE": "FAIL",
}


def main():
    text = open(SRC, encoding="utf-8").read()
    commit = git_commit(SRC)
    header, rows = find_table(text, ["image", "family", "status", "S_gate", "DeltaQ_budget (dB)"])
    idx = {h: k for k, h in enumerate(header)}

    data = []
    for r in rows:
        img = r[idx["image"]]
        if img.startswith("**"):          # the '**median S_gate**' summary row
            continue
        data.append(r)

    # cross-checks reprinted for the audit log
    sgate = [float(r[idx["S_gate"]]) for r in data]
    dq = [float(r[idx["DeltaQ_budget (dB)"]]) for r in data]
    n_sru = sum(1 for r in data if r[idx["status"]] == "SAFE_RANGE_UNINFORMATIVE")
    n_pos = sum(1 for x in dq if x > 0)
    print("[S2] source = %s (commit %s)" % (SRC, commit))
    print("[S2] n_images=%d  median S_gate=%.3f  SRU=%d/%d" %
          (len(data), statistics.median(sgate), n_sru, len(data)))
    print("[S2] median DeltaQ=%.3f dB  DeltaQ>0 in %d/%d" %
          (statistics.median(dq), n_pos, len(data)))
    lc = [r for r in data if r[idx["image"]] == "low_contrast"]
    fl = [r for r in data if r[idx["image"]] == "fine_lines"]
    if lc:
        print("[S2] stress low_contrast DeltaQ=%s dB" % lc[0][idx["DeltaQ_budget (dB)"]])
    if fl:
        print("[S2] stress fine_lines  DeltaQ=%s dB" % fl[0][idx["DeltaQ_budget (dB)"]])

    L = []
    L.append(r"%% S2: NATURAL-30 per-image endpoint table")
    L.append(r"%% GENERATED by code/round63/figs/supp_s2_natural.py -- do not edit by hand")
    L.append(r"%% source: results/round63_s2_natural/PILOT_SUMMARY.md (commit %s)" % commit)
    L.append(r"{\footnotesize")
    L.append(r"\setlength{\tabcolsep}{4pt}")
    L.append(r"\begin{longtable}{llcrrrrrrc}")
    L.append(r"\caption{Full NATURAL-30 cohort (secondary, no gate): per-image "
             r"acquisition-speed endpoint on the RQL arm, reproduced verbatim from "
             r"the frozen analyzer output. \textsc{sru} = "
             r"\textsc{safe\_range\_uninformative} ($S_{\mathrm{gate}}=1$ by the "
             r"frozen censoring taxonomy). $T_{\mathrm{safe}},T_{\mathrm{fast}}$ are "
             r"$Q_{90}$ crossing times (s); $R_j$ the safe-arm quality span; "
             r"$\Delta Q_{\mathrm{budget}}$ the fixed-dwell radiometric-PSNR gain at "
             r"$\nu=2000$. The two synthetic stress scenes bracket the cohort: "
             r"\texttt{low\_contrast} ($\Delta Q=-1.78$~dB, the only strongly "
             r"negative rung) and \texttt{fine\_lines} ($\Delta Q=+0.07$~dB). "
             r"Cohort median $S_{\mathrm{gate}}=5.70$; median $\Delta Q=+1.44$~dB, "
             r"positive in $29/30$ scenes; $12/30$ scenes safe-range-uninformative.}")
    L.append(r"\label{tab:s2_natural}\\")
    L.append(r"\toprule")
    head = (r"image & family & status & $S_{\mathrm{gate}}$ & $T_{\mathrm{safe}}$ & "
            r"$T_{\mathrm{fast}}$ & $R_j$ & $Q_{90}$ & $\Delta Q$ & seeds \\")
    L.append(head)
    L.append(r"\midrule")
    L.append(r"\endfirsthead")
    L.append(r"\toprule")
    L.append(head)
    L.append(r"\midrule")
    L.append(r"\endhead")
    L.append(r"\midrule")
    L.append(r"\multicolumn{10}{r}{\footnotesize continued on next page}\\")
    L.append(r"\endfoot")
    L.append(r"\bottomrule")
    L.append(r"\endlastfoot")

    for r in data:
        img = tt(r[idx["image"]])
        fam = tex_escape(r[idx["family"]])
        st = STATUS_SHORT.get(r[idx["status"]], tex_escape(r[idx["status"]]))
        cells = [img, fam, st,
                 r[idx["S_gate"]],
                 r[idx["T_safe"]] if r[idx["T_safe"]] != "--" else "--",
                 r[idx["T_fast"]] if r[idx["T_fast"]] != "--" else "--",
                 r[idx["R_j (dB)"]],
                 r[idx["Q90_j (dB)"]] if r[idx["Q90_j (dB)"]] != "--" else "--",
                 r[idx["DeltaQ_budget (dB)"]],
                 r[idx["seeds"]]]
        L.append(" & ".join(cells) + r" \\")
    L.append(r"\end{longtable}")
    L.append(r"}")
    write_fragment("S2_natural.tex", L)
    return 0


if __name__ == "__main__":
    sys.exit(main())
