"""SUPPLEMENT S3 -- complete detector-mismatch tables.

Source of record: results/round63_s2_s3/S3_ANCHORS.md. Two frozen markdown
tables are parsed verbatim:
  * section (b) main-text anchor subset (RQL/PRECORRECT dPSNR at safe & fast);
  * section (a) full variant table across every (variant, arm, rho_bar) group,
    including the severity sweeps (tau +/-0.2, dark 5/25/50%, afterpulsing to
    10%), the start/guard/jitter axes, and the MISSING paralyzable anchor.

The narrative notes preserved in the caption/paragraph: PRECORRECT safe-point
degeneracy (flux_dev = -1.0, floored), the dark50%-known un-flooring anomaly,
and the honestly-labelled MISSING paralyzable-data anchor.

Writes paper/supp_tables/S3_anchors.tex and paper/supp_tables/S3_full.tex.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from supp_common import REPO, tex_escape, tt, git_commit, find_table, write_fragment  # noqa: E402

SRC = os.path.join(REPO, "results", "round63_s2_s3", "S3_ANCHORS.md")


def main():
    text = open(SRC, encoding="utf-8").read()
    commit = git_commit(SRC)
    print("[S3] source = %s (commit %s)" % (SRC, commit))

    # ---- (b) main-text anchor subset -------------------------------------
    hb, rb = find_table(text, ["variant", "RQL dPSNR safe (rho=0.05)",
                               "PRECORRECT dPSNR fast"])
    ib = {h: k for k, h in enumerate(hb)}
    print("[S3] anchor subset rows = %d" % len(rb))

    A = []
    A.append(r"%% S3 (b): main-text detector-mismatch anchor subset")
    A.append(r"%% GENERATED by code/round63/figs/supp_s3_mismatch.py -- do not edit by hand")
    A.append(r"%% source: results/round63_s2_s3/S3_ANCHORS.md section (b) (commit %s)" % commit)
    A.append(r"\begin{table}[t]")
    A.append(r"\centering")
    A.append(r"\caption{Detector-mismatch anchor subset at the preregistered anchor "
             r"($M/n=0.5$, $\nu=500$, $64^2$), paired against the matched no-mismatch "
             r"baseline. Entries are median paired radiometric-PSNR shifts (dB); the "
             r"RQL flux bias is the variant's own median radiometric flux deviation at "
             r"the fast point. PRECORRECT dPSNR is reported at the fast point only: at "
             r"the safe point PRECORRECT is a degenerate floored reconstruction "
             r"($\mathrm{flux\_dev}=-1.0$ for all rows, identical to its own baseline), "
             r"so its safe dPSNR is trivially $\sim\!0$ and uninformative. The "
             r"paralyzable-data / non-paralyzable-model anchor is not instantiated in "
             r"the pilot and is reported \textsc{missing} rather than imputed.}")
    A.append(r"\label{tab:s3_anchors}")
    A.append(r"\begin{tabular}{lrrrr}")
    A.append(r"\toprule")
    A.append(r"variant & RQL safe & RQL fast & RQL flux bias & PRECORRECT fast \\")
    A.append(r" & (dB) & (dB) & (fast) & (dB) \\")
    A.append(r"\midrule")
    for r in rb:
        A.append(" & ".join([
            tex_escape(r[ib["variant"]]),
            r[ib["RQL dPSNR safe (rho=0.05)"]],
            r[ib["RQL dPSNR fast (rho=0.6)"]],
            r[ib["RQL flux bias fast"]],
            r[ib["PRECORRECT dPSNR fast"]],
        ]) + r" \\")
    A.append(r"\bottomrule")
    A.append(r"\end{tabular}")
    A.append(r"\end{table}")
    write_fragment("S3_anchors.tex", A)

    # ---- (a) full variant table ------------------------------------------
    ha, ra = find_table(text, ["variant", "arm", "rho_bar", "median PSNR_rad",
                               "dPSNR (vs baseline)", "method"])
    ia = {h: k for k, h in enumerate(ha)}
    print("[S3] full variant table rows = %d" % len(ra))

    F = []
    F.append(r"%% S3 (a): full detector-mismatch variant table")
    F.append(r"%% GENERATED by code/round63/figs/supp_s3_mismatch.py -- do not edit by hand")
    F.append(r"%% source: results/round63_s2_s3/S3_ANCHORS.md section (a) (commit %s)" % commit)
    F.append(r"{\footnotesize")
    F.append(r"\setlength{\tabcolsep}{4pt}")
    F.append(r"\begin{longtable}{llrrrrrlrr}")
    F.append(r"\caption{Complete detector-mismatch variant table: every "
             r"(variant, arm, $\bar\rho$) group at the $M/n=0.5$, $\nu=500$ anchor, "
             r"including the severity sweeps (dead-time error to $\pm20\%$, dark rate "
             r"$5$--$50\%$, afterpulsing to $10\%$) and the start-mode, guard-time and "
             r"dead-time-jitter axes. $n$ = rows in group; $n_{\mathrm{pair}}$ = "
             r"per-(image,seed) pairs used for the paired dPSNR; $\Delta\mathrm{flux}$ "
             r"is the difference of median radiometric flux deviations "
             r"(variant $-$ baseline). \textsc{missing} marks $\bar\rho=0.3$ "
             r"interaction cells with no matched baseline. The dark50\%-known "
             r"PRECORRECT safe row is the un-flooring anomaly: the normally floored "
             r"PRECORRECT safe reconstruction ($\mathrm{flux\_dev}=-1.0$) un-floors to "
             r"$\mathrm{flux\_dev}\approx0$ under a known $50\%$ dark rate, giving a "
             r"$-2.60$~dB paired shift. All values verbatim from the frozen artifact; "
             r"non-numeric PSNR dropped from medians, never imputed.}")
    F.append(r"\label{tab:s3_full}\\")
    F.append(r"\toprule")
    fhead = (r"variant & arm & $\bar\rho$ & med.\ PSNR & med.\ flux & $n$ & "
             r"dPSNR & method & $n_{\mathrm{pair}}$ & $\Delta$flux \\")
    F.append(fhead)
    F.append(r"\midrule")
    F.append(r"\endfirsthead")
    F.append(r"\toprule")
    F.append(fhead)
    F.append(r"\midrule")
    F.append(r"\endhead")
    F.append(r"\midrule")
    F.append(r"\multicolumn{10}{r}{\footnotesize continued on next page}\\")
    F.append(r"\endfoot")
    F.append(r"\bottomrule")
    F.append(r"\endlastfoot")
    for r in ra:
        F.append(" & ".join([
            tex_escape(r[ia["variant"]]),
            tex_escape(r[ia["arm"]]),
            r[ia["rho_bar"]],
            r[ia["median PSNR_rad"]],
            r[ia["median flux_dev"]],
            r[ia["n"]],
            r[ia["dPSNR (vs baseline)"]],
            tex_escape(r[ia["method"]]),
            r[ia["n_pair"]],
            r[ia["dflux"]],
        ]) + r" \\")
    F.append(r"\end{longtable}")
    F.append(r"}")
    write_fragment("S3_full.tex", F)
    return 0


if __name__ == "__main__":
    sys.exit(main())
