"""SUPPLEMENT S4 -- complete EXACT-TV vs RQL comparison.

Source of record: results/round63_s4/s4_rows.csv (paired EXACT-TV and RQL
reconstructions under the identical TV functional and the identical frozen
selection rule, at side in {8,16}). Pairs are formed on
(side, image, rho_bar, nu, seed); gap = PSNR_rad(EXACT-TV) - PSNR_rad(RQL).

Emits:
  * the 12x4 grid of the MEDIAN gap per (side, rho, nu) (2 sides x 6 rho rows,
    4 nu columns), plus the count of pairs in each cell;
  * the pair-level summary statistics (n pairs, exactly-identical pairs,
    max |gap|, fraction of pairs with |gap| > 0.1 dB, median gap).

Writes paper/supp_tables/S4_grid.tex.
"""
import os
import sys
import statistics
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from supp_common import REPO, to_float, load_csv, fnum, git_commit, write_fragment  # noqa: E402

SRC = os.path.join(REPO, "results", "round63_s4", "s4_rows.csv")
RHOS = [0.03, 0.1, 0.3, 0.6, 1.0, 2.0]
NUS = [20.0, 100.0, 500.0, 2000.0]
SIDES = [8, 16]


def main():
    rows = load_csv(SRC)
    commit = git_commit(SRC)
    key = lambda r: (int(to_float(r["side"])), r["image"], to_float(r["rho_bar"]),
                     to_float(r["nu"]), r["seed"])
    paired = defaultdict(dict)
    for r in rows:
        v = to_float(r["PSNR_rad"])
        if v is None:
            continue
        paired[key(r)][r["arm"]] = v

    gaps_all = []
    identical = 0
    cell = defaultdict(list)          # (side, rho, nu) -> [gap ...]
    for (side, img, rho, nu, seed), arms in paired.items():
        if "EXACT-TV" in arms and "RQL" in arms:
            g = arms["EXACT-TV"] - arms["RQL"]
            gaps_all.append(g)
            cell[(side, rho, nu)].append(g)
            if abs(g) < 1e-9:
                identical += 1

    n = len(gaps_all)
    n_big = sum(1 for g in gaps_all if abs(g) > 0.1)
    cell_med = {kk: statistics.median(v) for kk, v in cell.items()}
    # extreme-load corner = 16^2, rho>=0.6, nu=2000 (main-text definition)
    corner_cells = [(16, rho, 2000.0) for rho in RHOS if rho >= 0.6]
    corner = max((cell_med[c] for c in corner_cells if c in cell_med), key=abs)
    # deployment zone bound: rho<=1 median gaps, excluding the extreme corner
    zone_max = max(abs(m) for (s, rho, nu), m in cell_med.items()
                   if rho <= 1.0 and (s, rho, nu) not in corner_cells)
    stats = dict(n=n, identical=identical, max_abs=max(abs(g) for g in gaps_all),
                 frac_big=n_big / n, med=statistics.median(gaps_all),
                 zone_max=zone_max, corner=corner)
    print("[S4] source = %s (commit %s)" % (SRC, commit))
    print("[S4] pairs=%d identical=%d max|gap|=%.4f dB frac>0.1dB=%.4f median=%.4f" %
          (stats["n"], stats["identical"], stats["max_abs"], stats["frac_big"], stats["med"]))
    print("[S4] grid median gap (EXACT-TV - RQL), dB:")
    for side in SIDES:
        for rho in RHOS:
            cells = []
            for nu in NUS:
                g = cell.get((side, rho, nu), [])
                cells.append("%7s(%d)" % (fnum(statistics.median(g), 3, plus=True) if g else "--", len(g)))
            print("[S4]  side=%2d rho=%.2f : %s" % (side, rho, " ".join(cells)))

    L = []
    L.append(r"%% S4: EXACT-TV vs RQL median-gap grid + pair statistics")
    L.append(r"%% GENERATED by code/round63/figs/supp_s4_exact.py -- do not edit by hand")
    L.append(r"%% source: results/round63_s4/s4_rows.csv (commit %s)" % commit)
    L.append(r"\begin{table}[t]")
    L.append(r"\centering")
    L.append(r"\caption{Complete EXACT-TV versus RQL comparison on the frozen "
             r"$8^2$/$16^2$ grid (%d paired reconstructions). Cells give the median "
             r"radiometric-PSNR gap $\mathrm{PSNR}(\text{EXACT-TV})-"
             r"\mathrm{PSNR}(\text{RQL})$ in dB per $(\text{side},\bar\rho,\nu)$ "
             r"(pair count in parentheses; three seeds $\times$ six scenes per cell). "
             r"The median gap stays within $%.3f$~dB in magnitude throughout the "
             r"deployment zone ($\bar\rho\le1$) and reaches only $%s$~dB in the "
             r"extreme-load corner ($16^2$, $\bar\rho\ge0.6$, $\nu=2000$). Over all "
             r"pairs: %d exactly identical, median $%s$~dB, maximum "
             r"$|{\rm gap}|=%.2f$~dB, and only $%.1f\%%$ of pairs exceed $0.1$~dB in "
             r"either direction -- consistent with the nonconvexity of the exact "
             r"objective and with no systematic advantage to either arm.}"
             % (stats["n"], stats["zone_max"], fnum(stats["corner"], 2, plus=True),
                stats["identical"], fnum(stats["med"], 2, plus=True),
                stats["max_abs"], 100 * stats["frac_big"]))
    L.append(r"\label{tab:s4_grid}")
    L.append(r"\begin{tabular}{ll" + "r" * len(NUS) + "}")
    L.append(r"\toprule")
    L.append(r"side & $\bar\rho$ & " +
             " & ".join(r"$\nu{=}%d$" % int(nu) for nu in NUS) + r" \\")
    L.append(r"\midrule")
    for si, side in enumerate(SIDES):
        for ri, rho in enumerate(RHOS):
            lab = (r"\multirow{%d}{*}{$%d^2$}" % (len(RHOS), side)) if ri == 0 else ""
            cells = []
            for nu in NUS:
                g = cell.get((side, rho, nu), [])
                cells.append(fnum(statistics.median(g), 3, plus=True) if g else "--")
            L.append("%s & %s & %s \\\\" % (lab, fnum(rho, 2), " & ".join(cells)))
        if si == 0:
            L.append(r"\midrule")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")
    write_fragment("S4_grid.tex", L)
    return 0


if __name__ == "__main__":
    sys.exit(main())
