"""SUPPLEMENT S8 -- descriptive measurement-audit distributions.

Source of record: results/round63_s2_detail/pilot_rows.csv, audit columns
(audit_status, d_ratio, leak_suspect), which are populated only for the RQL arm
(the audit is descriptive and is excluded from selection, reconstruction, and
all pass/fail decisions). Reports, per (rho_bar, nu): the d_ratio quantiles
(5%, median, 95%, max) and the leak_suspect count, together with the overall
audit_status tally.

Writes paper/supp_tables/S8_audit.tex.
"""
import os
import sys
from collections import defaultdict, Counter

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from supp_common import REPO, to_float, load_csv, fnum, git_commit, write_fragment  # noqa: E402

SRC = os.path.join(REPO, "results", "round63_s2_detail", "pilot_rows.csv")


def main():
    rows = load_csv(SRC)
    commit = git_commit(SRC)
    rql = [r for r in rows if r["arm"] == "RQL"]
    status = Counter(r["audit_status"] for r in rql)
    leak_total = sum(1 for r in rql if r["leak_suspect"] == "True")

    by = defaultdict(lambda: {"d": [], "leak": 0})
    for r in rql:
        rho = to_float(r["rho_bar"])
        nu = to_float(r["nu"])
        v = to_float(r["d_ratio"])
        if v is not None:
            by[(rho, nu)]["d"].append(v)
        if r["leak_suspect"] == "True":
            by[(rho, nu)]["leak"] += 1

    rhos = sorted(set(k[0] for k in by))
    nus = sorted(set(k[1] for k in by))
    print("[S8] source = %s (commit %s)" % (SRC, commit))
    print("[S8] RQL rows=%d  audit_status=%s  leak_suspect True=%d/%d" %
          (len(rql), dict(status), leak_total, len(rql)))

    rows_out = []
    for rho in rhos:
        for nu in nus:
            cellv = by.get((rho, nu))
            if not cellv or not cellv["d"]:
                continue
            a = np.asarray(cellv["d"])
            q = np.percentile(a, [5, 50, 95, 100])
            rows_out.append((rho, nu, len(a), q[0], q[1], q[2], q[3], cellv["leak"]))
            print("[S8]  rho=%.2f nu=%5d n=%d d_ratio q05/med/q95/max=%.3f/%.3f/%.3f/%.3f leak=%d"
                  % (rho, nu, len(a), q[0], q[1], q[2], q[3], cellv["leak"]))

    L = []
    L.append(r"%% S8: descriptive measurement-audit distributions")
    L.append(r"%% GENERATED by code/round63/figs/supp_s8_audit.py -- do not edit by hand")
    L.append(r"%% source: results/round63_s2_detail/pilot_rows.csv (commit %s)" % commit)
    L.append(r"{\footnotesize")
    L.append(r"\setlength{\tabcolsep}{5pt}")
    L.append(r"\begin{longtable}{rrrrrrrr}")
    L.append(r"\caption{Descriptive measurement-audit distributions on the RQL arm "
             r"of the $64^2$ detail cohort ($%d$ audited cells; $\mathrm{audit\_status}"
             r"=\textsc{ok}$ for all $%d/%d$). Per $(\bar\rho,\nu)$: the "
             r"refit-bootstrap discrepancy-ratio $d_{\mathrm{ratio}}$ quantiles and the "
             r"count of leak-suspect cells (True in $%d$ of $%d$ cells overall). "
             r"\emph{The audit is descriptive and is not a model-adequacy test:} all "
             r"audit statistics are excluded from regularization selection, "
             r"reconstruction, cell inclusion, and every confirmatory pass/fail "
             r"decision. The reference distribution is conditional on a smoothed "
             r"plug-in scene, so its tail ranks are not calibrated model-class "
             r"$p$-values and can be anti-conservative when the true scene is rougher "
             r"than the plug-in.}"
             % (len(rql), status.get("OK", 0), len(rql), leak_total, len(rql)))
    L.append(r"\label{tab:s8_audit}\\")
    L.append(r"\toprule")
    head = (r"$\bar\rho$ & $\nu$ & $n$ & $d_{5\%}$ & $d_{50\%}$ & $d_{95\%}$ & "
            r"$d_{\max}$ & leak \\")
    L.append(head)
    L.append(r"\midrule")
    L.append(r"\endfirsthead")
    L.append(r"\toprule")
    L.append(head)
    L.append(r"\midrule")
    L.append(r"\endhead")
    L.append(r"\midrule")
    L.append(r"\multicolumn{8}{r}{\footnotesize continued on next page}\\")
    L.append(r"\endfoot")
    L.append(r"\bottomrule")
    L.append(r"\endlastfoot")
    last_rho = None
    for (rho, nu, n, q05, q50, q95, qmax, leak) in rows_out:
        if last_rho is not None and rho != last_rho:
            L.append(r"\addlinespace")
        last_rho = rho
        L.append("%s & %d & %d & %s & %s & %s & %s & %d \\\\" % (
            fnum(rho, 2), int(nu), n, fnum(q05, 3), fnum(q50, 3), fnum(q95, 3),
            fnum(qmax, 3), leak))
    L.append(r"\end{longtable}")
    L.append(r"}")
    write_fragment("S8_audit.tex", L)
    return 0


if __name__ == "__main__":
    sys.exit(main())
